transmission-daemon:
  extends:
    file: docker-compose.common.yml
    service: transmission-daemon
  restart: unless-stopped
  environment:
    - TRANSMISSION_USER
    - TRANSMISSION_PASS
  command:
    - "--allowed=*"
    - "--rpc-bind-address=0.0.0.0"
    - "--encryption-preferred"
    - "--dht"
    - "--utp"
    - "--lpd"
    - "--portmap"
    - "--no-global-seedratio"
    - "--auth"
    - "--username=${TRANSMISSION_USER}"
    - "--password=${TRANSMISSION_PASS}"
    - "--watch-dir=/root/.config/transmission-daemon/watch/"
#    - "-d" # Dump transmission-daemon's settings to stderr.
  net: host
#  ports:
#    - 127.0.0.1:9091:9091
#    - 51413:51413

minidlna:
  container_name: transmission-minidlna
  image: pataquets/minidlna
  restart: unless-stopped
  command: [ "-d" ]
  net: host
  volumes:
    - ~/transmission/downloads/:/var/lib/minidlna/:ro
